FROM centos
ENV MYPATH /usr/local/blogger
RUN mkdir /usr/local/blogger
RUN mkdir /usr/local/blogger/conf
ADD featherwit-blogger /usr/local/blogger
COPY conf/config.json /usr/local/blogger/conf
RUN chmod 777 /usr/local/blogger/featherwit-blogger
WORKDIR $MYPATH
EXPOSE 8080
CMD [ "./featherwit-blogger" ]
